apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-dir
  namespace: kube-system
data:
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDK8jeUNU59zCpLEYNJyyPNRgTPXXZowo4Fg8xI33WCHeIZqPj6OHN5WtWLgHt4v+uwB0KxqHOtO8tB3qfONSbKFsniF8MrboEVxOJgz37ACDd+pZqGsbtJU+H8+c0Ompk11kpB+NT+x6IlJvgpFEZTBvDV37QOzME1YiBB4oJqWL5BP25QPLIGjHdWAjp6sQichd7RACvjAShGOsJs3M94hL4uu/a4ggOnxX6p4lWQo7mpg4ytw+yghsDyLX0lM/cyUJp7BkGTya9VapHDOuQgS4HOYz+I3lpmAvUrxLf7qQ1mpQHUnrCcXaVYf5eKdPQKSv7wGIsQ5P20wiX+8xgj1SvoSqmswHDn5fl01QpOMryYfWkkVlLho5lmpo7Lg23YlfQTuowktuUfAM8Ji/HO4tzaIK/sPXX3ZmfMFkBbZEaQsoRkwEMSHtkh4Xo15UjQ2cEntHCmd0ml38aqxtwn31fhT5pWYA9vOR90OkNiFNLkWZq82722WVRsCVPQjZwYs61vLi/LzOoEEiYuKhBfWSrXqUqS+VB/2KVWSxQnC55jxzqjQWmhFsvuXEPGtLgqpMQvr4hhzstp2B/8nBRmX2EBtsAwCZiwDCHVs+LM9WEyhAqemNamy2XtIWWmXTZUa2vg+zkkWSZOxxuaDkTZxm+Bpjrc2kpuA088HTL8Iw== cardno:000604946386
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: debug-tools
  name: debug-tools
  namespace: kube-system
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: debug-tools
  template:
    metadata:
      labels:
        app: debug-tools
    spec:
      containers:
      - image: ghcr.io/aarnaud/talos-debug-tools:latest-6.1.78
        imagePullPolicy: IfNotPresent
        name: debug-container
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: hostfs
            mountPath: /rootfs
          - name: run-containerd
            mountPath: /run/containerd
          - name: var-log-pods
            mountPath: /var/log/pods
          - name: ssh-dir
            mountPath: /root/.ssh/authorized_keys
            subPath: authorized_keys
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostPID: true
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - name: hostfs
          hostPath:
            path: /
        - name: run-containerd
          hostPath:
            path: /run/containerd
        - name: var-log-pods
          hostPath:
            path: /var/log/pods
        - name: ssh-dir
          configMap:
            name: ssh-dir
            defaultMode: 0700
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate