apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-dir
  namespace: kube-system
data:
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1....
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: debug-tools
  name: debug-tools
  namespace: kube-system
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: debug-tools
  template:
    metadata:
      labels:
        app: debug-tools
    spec:
      containers:
      - image: ghcr.io/aarnaud/talos-debug-tools:latest-6.1.80
        imagePullPolicy: IfNotPresent
        name: debug-container
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: hostfs
            mountPath: /host
          - name: device-dir
            mountPath: /dev
          - name: run-containerd
            mountPath: /run/containerd
          - name: var-log-pods
            mountPath: /var/log/pods
          - name: ssh-dir
            mountPath: /root/.ssh/authorized_keys
            subPath: authorized_keys
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostPID: true
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - name: hostfs
          hostPath:
            path: /
        - name: device-dir
          hostPath:
            path: /dev
        - name: run-containerd
          hostPath:
            path: /run/containerd
        - name: var-log-pods
          hostPath:
            path: /var/log/pods
        - name: ssh-dir
          configMap:
            name: ssh-dir
            defaultMode: 0700
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
